service: html-parser

frameworkVersion: "=1.13.2"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1

functions:
  parse:
    handler: handler.parse
    events:
      - http:
          path: /parse
          method: get
